"""set tg_id unique

Revision ID: 5c97b024f8ff
Revises: 1a43900668e6
Create Date: 2025-03-19 22:34:26.162536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c97b024f8ff"
down_revision: Union[str, None] = "1a43900668e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_tg_id"), "users", ["tg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_tg_id"), "users", type_="unique")
    # ### end Alembic commands ###
